---
# tasks file for install_client

# ------------------------------------------------------------------------------
- name: "CLIENT | vscode | check if vs code is installed - {{ outer_item.name }}"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.shell: set -o pipefail && command -v code >/dev/null 2>&1
  args:
    executable: /bin/bash
  register: is_code_exist
  changed_when: is_code_exist.rc != 0
  # ignore_errors: true
  tags:
    - install_client
    - vs_code

# ------------------------------------------------------------------------------
# `$code --list-extensions | xargs -L 1 echo code --install-extension`
- name: "CLIENT | vscode | install vs-code extensions - {{ outer_item.name }}"
  become: true
  become_user: "{{ outer_item.name }}"
  # command: "code --list-extensions | grep {{ item }} -q || code --install-extension {{ item }} && true"
  ansible.builtin.command: "code --install-extension {{ item }}"
  loop: "{{ install_client_vs_code_ext | flatten(levels=1) }}"
  changed_when: false
  failed_when: false
  when: install_client_vs_code_ext is defined and (is_code_exist.rc is defined and is_code_exist.rc == 0)
  tags:
    - install_client
    - vs_code

# ------------------------------------------------------------------------------
- name: "CLIENT | vscode | copy template for vs-code settings.json - {{ outer_item.name }}"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.template:
    src: vs-settings.json.j2
    dest: "~/.config/Code/User/settings.json"
    mode: "0664"
  when: (is_code_exist.rc is defined and is_code_exist.rc == 0)
  tags:
    - install_client
    - vs_code

- name: "CLIENT | vscode | copy template for vs-code keybindings.json - {{ outer_item.name }}"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.template:
    src: vs-keybindings.json.j2
    dest: "~/.config/Code/User/keybindings.json"
    mode: "0664"
  when: (is_code_exist.rc is defined and is_code_exist.rc == 0)
  tags:
    - install_client
    - vs_code
