---
# tasks file for install_client

# ------------------------------------------------------------------------------
- name: "CLIENT | AppImage | create folder"
  ansible.builtin.file:
    path: "/opt/{{ outer_item.name }}/"
    state: directory
    mode: "1755"
  tags:
    - install_client
    - apt

- name: "CLIENT | AppImage | get the image"
  ansible.builtin.get_url:
    url: "{{ outer_item.app_image }}"
    dest: "/opt/{{ outer_item.name }}/{{ outer_item.name }}.AppImage"
    mode: "0665"
    # checksum: sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
  tags:
    - install_client
    - apt

- name: "CLIENT | AppImage | get the image"
  ansible.builtin.get_url:
    url: "{{ outer_item.png }}"
    dest: "/opt/{{ outer_item.name }}/{{ outer_item.name }}.png"
    mode: "0664"
    # checksum: sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
  tags:
    - install_client
    - apt

- name: "CLIENT | AppImage | create file .desktop"
  ansible.builtin.template:
    src: template.desktop.j2
    dest: "/usr/share/applications/{{ outer_item.name }}.desktop"
    owner: root
    group: root
    mode: "0644"
  tags:
    - install_client
    - apt
