---
# tasks file for install_client

# ------------------------------------------------------------------------------
# CHECK IF SERVICE INSTALLED
- name: "CLIENT | snap | check if service installed"
  become: true
  ansible.builtin.command: which snap
  register: is_snap_exist
  changed_when: false
  failed_when: false
  when:
    - install_client_snap is defined
  tags:
    - install_client
    - snap

# ------------------------------------------------------------------------------
- name: "CLIENT | snap | start udev and snapd"
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - udev
    - snapd
  when:
    - install_client_snap is defined
    - is_snap_exist.rc is defined
    - is_snap_exist.rc == 0
  tags:
    - molecule-idempotence-notest
    - install_client
    - snap

# ------------------------------------------------------------------------------
- name: "CLIENT | snap | install snap services"
  become: true
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | default('no') | bool }}"
    # beta: "{{ item.beta | default('no') | bool }}"
  loop: "{{ install_client_snap | flatten(levels=1) }}"
  when:
    - install_client_snap is defined
    - is_snap_exist.rc is defined
    - is_snap_exist.rc == 0
    - item.install is defined
    - item.install | bool
  tags:
    - install_client
    - snap
