---
# tasks file for install_client

# ------------------------------------------------------------------------------
- name: install apt services [main]
  become: true
  ansible.builtin.apt:
    pkg: "{{ item.name }}"
    state: present
    force_apt_get: true # apt-get instead of aptitude
  loop: "{{ install_client_apt|flatten(levels=1) }}"
  when: (install_client_apt is defined) and (item.install is defined and item.install | bool)
  tags:
    - install_client
    - apt
