---
# tasks file for install_client

# ------------------------------------------------------------------------------
- name: "create a directory for fonts"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.file:
    path: "{{ install_client_fonts.path }}"
    state: directory
    mode: "0754"
  tags:
    - install_client
    - fonts

# ------------------------------------------------------------------------------
- name: "download and unarchive fonts"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: "{{ install_client_fonts.path }}"
    remote_src: yes
  loop: "{{ install_client_fonts.url | flatten(levels=1) }}"
  tags:
    - install_client
    - fonts
