---
# tasks file for install_client

# ------------------------------------------------------------------------------
# FLATPAK IT SELF
- name: flatpak - install it self
  become: true
  apt:
    pkg: flatpak
    state: present
    force_apt_get: yes # apt-get instead of aptitude
  when: (install_client_flatpak is defined)
  tags:
    - install_client
    - flatpak

# ------------------------------------------------------------------------------
# REMOTE ADD
- name: flatpak - add remote flathub
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    # method: user
  when: (install_client_flatpak is defined)
  tags:
    - install_client
    - flatpak

# ------------------------------------------------------------------------------
# CHECK IF SERVICE INSTALLED
- name: flatpak - check if service installed
  become: true
  shell: command -v flatpak >/dev/null 2>&1
  register: is_flatpak_exist
  ignore_errors: yes
  tags:
    - install_client
    - flatpak

# ------------------------------------------------------------------------------
# INSTALL
- name: flatpak - install services
  become: true
  community.general.flatpak:
    name: "{{ item.name }}"
    remote: "{{ item.remote | default('flathub') }}"
    # method: user
  loop: "{{ install_client_flatpak|flatten(levels=1) }}"
  when: (install_client_flatpak is defined) and (item.install is defined and item.install | bool) and (is_flatpak_exist.rc is defined and is_flatpak_exist.rc == 0)
  tags:
    - install_client
    - flatpak
