---
# tasks file for install_client

# ------------------------------------------------------------------------------
# NOTE: removed section, current available in server installer, will maybe moved later here
