---
# tasks file for install_client

# ------------------------------------------------------------------------------
- name: "CLIENT | apt | install apt services"
  become: true
  ansible.builtin.apt:
    pkg: "{{ item.name }}"
    state: present
    force_apt_get: true # apt-get instead of aptitude
    update_cache: true
  loop: "{{ install_client_apt | flatten(levels=1) }}"
  when:
    - install_client_apt is defined
    - item.install is defined
    - item.install | bool
  tags:
    - install_client
    - apt
