---
# tasks file for install_client

# ------------------------------------------------------------------------------
- name: "CLIENT | AppImage | create folder"
  become: true
  ansible.builtin.file:
    path: "/opt/{{ outer_item.name }}/"
    state: directory
    mode: "1755"
  tags:
    - install_client
    - apt

- name: "CLIENT | AppImage | get AppImage"
  become: true
  ansible.builtin.get_url:
    url: "{{ outer_item.app_image }}"
    dest: "/opt/{{ outer_item.name }}/{{ outer_item.name }}.AppImage"
    mode: "0755"
    # checksum: sha256:...
  tags:
    - install_client
    - apt

- name: "CLIENT | AppImage | get image (png)"
  become: true
  ansible.builtin.get_url:
    url: "{{ outer_item.png }}"
    dest: "/opt/{{ outer_item.name }}/{{ outer_item.name }}.png"
    mode: "0644"
    # checksum: sha256:...
  tags:
    - install_client
    - apt

- name: "CLIENT | AppImage | create file .desktop"
  become: true
  ansible.builtin.template:
    src: template.desktop.j2
    dest: "/usr/share/applications/{{ outer_item.name }}.desktop"
    owner: root
    group: root
    mode: "0644"
  tags:
    - install_client
    - apt
