---
# tasks file for install_client

# ------------------------------------------------------------------------------
- name: "check if vs code is installed (for user: {{ outer_item.name }})"
  become: yes
  become_user: "{{ outer_item.name }}"
  shell: command -v code >/dev/null 2>&1
  register: is_code_exist
  ignore_errors: yes
  tags:
    - install_client
    - vs_code

# ------------------------------------------------------------------------------
# `$code --list-extensions | xargs -L 1 echo code --install-extension`
- name: "install vs-code extensions (for user: {{ outer_item.name }})"
  become: yes
  become_user: "{{ outer_item.name }}"
  # command: "code --list-extensions | grep {{ item }} -q || code --install-extension {{ item }} && true"
  command: "code --install-extension {{ item }}"
  loop: "{{ install_client_vs_code_ext|flatten(levels=1) }}"
  when: install_client_vs_code_ext is defined and (is_code_exist.rc is defined and is_code_exist.rc == 0)
  ignore_errors: yes
  tags:
    - install_client
    - vs_code

# ------------------------------------------------------------------------------
- name: "copy template for vs-code settings.json (for user: {{ outer_item.name }})"
  become: yes
  become_user: "{{ outer_item.name }}"
  template:
    src: vs-settings.json.j2
    dest: "~/.config/Code/User/settings.json"
    mode: "0664"
  when: (is_code_exist.rc is defined and is_code_exist.rc == 0)
  tags:
    - install_client
    - vs_code

- name: "copy template for vs-code keybindings.json (for user: {{ outer_item.name }})"
  become: yes
  become_user: "{{ outer_item.name }}"
  template:
    src: vs-keybindings.json.j2
    dest: "~/.config/Code/User/keybindings.json"
    mode: "0664"
  when: (is_code_exist.rc is defined and is_code_exist.rc == 0)
  tags:
    - install_client
    - vs_code
