---
# tasks file for install_client

# ------------------------------------------------------------------------------
# CHECK IF SERVICE INSTALLED
- name: snap - check if service installed
  become: true
  ansible.builtin.shell: set -o pipefail && command -v snap >/dev/null 2>&1
  args:
    executable: /bin/bash
  register: is_snap_exist
  changed_when: is_snap_exist.rc != 0
  # ignore_errors: true
  tags:
    - install_client
    - snap

# ------------------------------------------------------------------------------
- name: install snap services [main]
  become: true
  snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | bool }}"
    # beta: "{{ item.beta | bool }}"
  loop: "{{ install_client_snap|flatten(levels=1) }}"
  when: (install_client_snap is defined) and (item.install is defined and item.install | bool) and (is_snap_exist.rc is defined and is_snap_exist.rc == 0)
  tags:
    - install_client
    - snap
