---
# tasks file for install_client

# ------------------------------------------------------------------------------
# FLATPAK IT SELF
- name: "CLIENT | flatpak | install it self"
  become: true
  ansible.builtin.apt:
    pkg: flatpak
    state: present
    force_apt_get: true # apt-get instead of aptitude
  when:
    - install_client_config is defined
    - install_client_config.apt_flatpak is defined
    - install_client_config.apt_flatpak | bool
    - install_client_flatpak is defined
  tags:
    - install_client
    - flatpak

# ------------------------------------------------------------------------------
# CHECK IF SERVICE INSTALLED
- name: "CLIENT | flatpak | check if service installed"
  become: true
  # become_user: "{{ outer_item.name }}"
  ansible.builtin.command: which flatpak
  register: is_flatpak_exist
  changed_when: false
  failed_when: false
  tags:
    - install_client
    - flatpak

# ------------------------------------------------------------------------------
# REMOTE ADD
- name: "CLIENT | flatpak | add remote flathub"
  become: true
  community.general.flatpak_remote:
    name: "{{ item.name }}"
    state: present
    flatpakrepo_url: "{{ item.url }}"
    method: "{{ item.method }}"
  loop: "{{ install_client_flatpak_remotes | flatten(levels=1) }}"
  register: is_flatpak_remote_added
  when:
    - install_client_flatpak_remotes is defined
    - install_client_flatpak is defined
    - item.install is defined
    - item.install | bool
    - is_flatpak_exist.rc is defined
    - is_flatpak_exist.rc == 0
  tags:
    - install_client
    - flatpak

# ------------------------------------------------------------------------------
# INSTALL
- name: "CLIENT | flatpak | install services"
  become: true
  # become_user: "{{ outer_item.name }}"
  community.general.flatpak:
    name: "{{ item.name }}"
    remote: "{{ item.remote | default('flathub') }}"
    state: present
    method: system
  loop: "{{ install_client_flatpak | flatten(levels=1) }}"
  when:
    - install_client_flatpak is defined
    - item.install is defined
    - item.install | bool
    - is_flatpak_exist.rc is defined
    - is_flatpak_exist.rc == 0
  tags:
    - install_client
    - flatpak
