---
# tasks file for ./roles/install_client

# ------------------------------------------------------------------------------
- name: install java packages [apt]
  become: true
  ansible.builtin.apt:
    pkg: "{{ install_client_java.apt }}"
    state: present
    force_apt_get: true # apt-get instead of aptitude
  when: install_client_java is defined and install_client_java.apt is defined
  tags:
    - install_client
    - install_java

# ------------------------------------------------------------------------------
- name: install java packages [apt]
  become: true
  ansible.builtin.apt:
    pkg: "{{ install_client_java.apt }}"
    state: present
    force_apt_get: true # apt-get instead of aptitude
  when: (install_client_config.dev is defined and install_client_config.dev | bool) and (install_client_java is defined and install_client_java.dev is defined)
  tags:
    - install_client
    - install_java

# ------------------------------------------------------------------------------

- name: set java env variables
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.variable }}="
    line: "{{ item.variable }}={{ item.path }}"
  with_items: "{{ install_client_java.os_env }}"
  tags:
    - install_client
    - install_java
