---
# tasks file for ./roles/install_client

# ------------------------------------------------------------------------------
- name: "CLIENT | java | install java packages"
  become: true
  ansible.builtin.apt:
    pkg: "{{ item.name }}"
    state: present
    force_apt_get: true # apt-get instead of aptitude
    update_cache: true
  loop: "{{ install_client_java.apt | flatten(levels=1) }}"
  when:
    - install_client_java is defined
    - install_client_java.apt is defined
    - item.install is defined
    - item.install | bool
  tags:
    - install_client
    - install_java

# ------------------------------------------------------------------------------

- name: "CLIENT | java | set java env variables into /etc/environment"
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.variable }}="
    line: "{{ item.variable }}={{ item.path }}"
  loop: "{{ install_client_java.os_env | flatten(levels=1) }}"
  when:
    - install_client_java is defined
    - install_client_java.os_env is defined
    - item.variable is defined
    - item.path is defined
  tags:
    - install_client
    - install_java
