---
# tasks file for install_client

# ------------------------------------------------------------------------------
- name: add apt signing key (trusted.gpg.d) (curl command for now)
  become: true
  # apt_key:
  #   id: "{{ item.id }}"
  #   url: "{{ item.url }}"
  #   keyring: "/etc/apt/trusted.gpg.d/{{ item.name }}"
  #   state: present
  shell: curl -sL "{{ item.url }}" | gpg --dearmor | tee /etc/apt/trusted.gpg.d/{{ item.name }} >/dev/null
  loop: "{{ outer_item.gpg | flatten(levels=1) }}"
  when: (outer_item.install is defined and outer_item.install | bool)
  tags:
    - install_client
    - distribution_key

# ------------------------------------------------------------------------------
- name: get OS distribution
  command: lsb_release -sc
  register: os_distribution
  when: (outer_item.install is defined and outer_item.install | bool)
  tags:
    - install_client
    - distribution_key

- name: get OS architecture
  shell: dpkg --print-architecture
  register: os_architecture
  when: (outer_item.install is defined and outer_item.install | bool)
  tags:
    - install_client
    - distribution_key

- name: add repository into sources list
  become: true
  apt_repository:
    repo: "deb [arch={{ os_architecture.stdout }}] {{ outer_item.repo }} {{ outer_item.distribution|default(os_distribution.stdout) }} {{ outer_item.version }}"
    state: present
  ignore_errors: yes
  when: (outer_item.install is defined and outer_item.install | bool)
  tags:
    - install_client
    - distribution_key

# ------------------------------------------------------------------------------
- name: install apt services
  become: true
  apt:
    pkg: "{{ item }}"
    state: present
    force_apt_get: yes # apt-get instead of aptitude
  loop: "{{ outer_item.apt|flatten(levels=1) }}"
  ignore_errors: yes
  when: (outer_item.install is defined and outer_item.install | bool)
  tags:
    - install_client
    - distribution_key
