---
# tasks file for install_client

# ------------------------------------------------------------------------------
- name: "CLIENT | dist-apt | add apt signing key, will not download if present"
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ install_client_distribution_key_keyring_path }}/{{ item.name }}"
    mode: "0644"
    force: true
    # id: "{{ item.id | default(omit) }}"
  loop: "{{ outer_item.gpg | flatten(levels=1) }}"
  tags:
    - install_client
    - distribution_key

# ------------------------------------------------------------------------------
- name: "CLIENT | dist-apt | get OS distribution"
  ansible.builtin.command: lsb_release -sc
  changed_when: false
  register: os_distribution
  tags:
    - install_client
    - distribution_key

- name: "CLIENT | dist-apt | get OS architecture"
  ansible.builtin.command: dpkg --print-architecture
  changed_when: false
  register: os_architecture
  tags:
    - install_client
    - distribution_key

- name: "CLIENT | dist-apt | add repository into sources list"
  become: true
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ os_architecture.stdout }} signed-by={{ install_client_distribution_key_keyring_path }}/{{ item.name }}] {{ outer_item.repo }} {{ outer_item.distribution | default(os_distribution.stdout) }} {{ outer_item.version }}
    state: present
  loop: "{{ outer_item.gpg | flatten(levels=1) }}"
  tags:
    - install_client
    - distribution_key

# ------------------------------------------------------------------------------
- name: "CLIENT | dist-apt | install apt services"
  become: true
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
    force_apt_get: true # apt-get instead of aptitude
    update_cache: true
  loop: "{{ outer_item.apt | flatten(levels=1) }}"
  tags:
    - install_client
    - distribution_key
