---
# tasks file for install_client

# ------------------------------------------------------------------------------
- name: "CLIENT | dist-apt | add apt signing key, will not download if present"
  ansible.builtin.apt_key:
    url: "{{ item.url }}"
    keyring: "/etc/apt/trusted.gpg.d/{{ item.name }}"
    state: present
  loop: "{{ outer_item.gpg | flatten(levels=1) }}"
  when:
    - outer_item.install is defined
    - outer_item.install | bool
  tags:
    - install_client
    - distribution_key

# ------------------------------------------------------------------------------
- name: "CLIENT | dist-apt | get OS distribution"
  ansible.builtin.command: lsb_release -sc
  register: os_distribution
  changed_when: false
  failed_when: false
  when:
    - outer_item.install is defined
    - outer_item.install | bool
  tags:
    - install_client
    - distribution_key

- name: "CLIENT | dist-apt | get OS architecture"
  ansible.builtin.command: dpkg --print-architecture
  register: os_architecture
  changed_when: false
  failed_when: false
  when:
    - outer_item.install is defined
    - outer_item.install | bool
  tags:
    - install_client
    - distribution_key

- name: "CLIENT | dist-apt | add repository into sources list"
  become: true
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ os_architecture.stdout }}] {{ outer_item.repo }} {{ outer_item.distribution | default(os_distribution.stdout) }} {{ outer_item.version }}
    state: present
  # ignore_errors: yes
  when:
    - outer_item.install is defined
    - outer_item.install | bool
  tags:
    - install_client
    - distribution_key

# ------------------------------------------------------------------------------
- name: "CLIENT | dist-apt | install apt services"
  become: true
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
    force_apt_get: true # apt-get instead of aptitude
  loop: "{{ outer_item.apt | flatten(levels=1) }}"
  # ignore_errors: yes
  when:
    - outer_item.install is defined
    - outer_item.install | bool
  tags:
    - install_client
    - distribution_key
