---
# tasks file for install_client

# # ------------------------------------------------------------------------------
# # SETUP USERS
# - name: "CLIENT | users | setup users"
#   ansible.builtin.include_tasks: setup_users.yml

# ------------------------------------------------------------------------------
# INSTALL SPECIFIC SERVICES - BY APT
- name: "CLIENT | apt | install apt services"
  ansible.builtin.include_tasks: install_apt.yml

# ------------------------------------------------------------------------------
# INSTALL SPECIFIC SERVICES - BY DPKG
- name: "CLIENT | dpkg | install dpkg services"
  ansible.builtin.include_tasks: install_dpkg.yml

# ------------------------------------------------------------------------------
# INSTALL SPECIFIC SERVICES - BY APPIMAGE
- name: "CLIENT | AppImage | install AppImage services"
  ansible.builtin.include_tasks: install_app_image.yml
  loop: "{{ install_client_app_image | flatten(levels=1) }}"
  loop_control:
    loop_var: outer_item
  when:
    - install_client_app_image is defined
    - outer_item.install is defined
    - outer_item.install | bool

# ------------------------------------------------------------------------------
# INSTALL SPECIFIC SERVICES - BY DISTRIBUTION KEY
- name: "CLIENT | dist_apt | install distribution services"
  ansible.builtin.include_tasks: install_extra_distribution_key.yml
  loop: "{{ install_client_distribution_key | flatten(levels=1) }}"
  loop_control:
    loop_var: outer_item
  when:
    - install_client_distribution_key is defined
    - outer_item.install is defined
    - outer_item.install | bool

# ------------------------------------------------------------------------------
# INSTALL SPECIFIC SERVICES - BY SNAP
- name: "CLIENT | snap | install snap services"
  ansible.builtin.include_tasks: install_snap.yml

# ------------------------------------------------------------------------------
# INSTALL SPECIFIC SERVICES - BY FLATPAK
- name: "CLIENT | flatpak | install flatpak services"
  ansible.builtin.include_tasks: install_flatpak.yml

# ------------------------------------------------------------------------------
# EXTEND VSCODE WITH ADDITIONALES
- name: "CLIENT | user - vscode | install code extras (per user)"
  ansible.builtin.include_tasks: install_per_user_code_extra.yml
  loop: "{{ clients | flatten(levels=1) }}"
  loop_control:
    loop_var: outer_item
  when:
    - install_client_config.vs_code_ext is defined
    - install_client_config.vs_code_ext | bool
    - (outer_item.setup is not defined or outer_item.setup | bool)

# ------------------------------------------------------------------------------
# GNOME SETUP (FAVORITES)
- name: "CLIENT | user - gnome | setup gnome (per user)"
  ansible.builtin.include_tasks: setup_gnome.yml
  loop: "{{ clients | flatten(levels=1) }}"
  loop_control:
    loop_var: outer_item
  when:
    - install_client_config.gnome_gui_setup is defined
    - install_client_config.gnome_gui_setup | bool
    - (outer_item.setup is not defined or outer_item.setup | bool)

# ------------------------------------------------------------------------------
# OTHER SETUPS
- name: "CLIENT | other | setup other settings"
  ansible.builtin.include_tasks: setup_other.yml

- name: "CLIENT | other | setup firefox ext and profile (per user)"
  ansible.builtin.include_tasks: setup_firefox.yml
  loop: "{{ clients | flatten(levels=1) }}"
  loop_control:
    loop_var: outer_item
  when:
    - install_client_config.firefox_setup is defined
    - install_client_config.firefox_setup | bool
    - (outer_item.setup is not defined or outer_item.setup | bool)

# ------------------------------------------------------------------------------
# POST
- name: "CLIENT | post | post setups"
  ansible.builtin.include_tasks: post.yml
