---
# tasks file for install_client

# --------------------------------------------------------------------------
- name: "CLIENT | firefox setup | check if Firefox is installed"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.command: "command -v firefox >/dev/null 2>&1"
  register: is_firefox_installed
  changed_when: false
  check_mode: false
  failed_when: false
  tags:
    - install_client
    - firefox

# --------------------------------------------------------------------------
- name: "CLIENT | firefox setup | check if default Firefox profile exists"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.stat:
    path: "~/{{ install_client_firefox_path }}/*.default"
  register: firefox_profile_output
  changed_when: false
  tags:
    - install_client
    - firefox

- name: "CLIENT | firefox setup | save default profile name"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.set_fact:
    install_client_firefox_profile_name: >
      {{ lookup('pipe', "ls -d ~/{{ install_client_firefox_path }}/*.default | awk -F/ '{print $NF}'") }}
  when: firefox_profile_output.stat.exists
  tags:
    - install_client
    - firefox

# --------------------------------------------------------------------------
- name: "CLIENT | firefox setup | create new Firefox profile"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.command: "firefox --headless --createprofile {{ install_client_firefox_profile_name }}"
  changed_when: false
  failed_when: false
  when: not firefox_profile_output.stat.exists
  tags:
    - install_client
    - firefox

- name: "CLIENT | firefox setup | save new created profile name"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.set_fact:
    install_client_firefox_profile_name: >
      {{ lookup('pipe', "ls -d ~/{{ install_client_firefox_path }}/*.{{ install_client_firefox_profile_name }} | awk -F/ '{print $NF}'") }}
  when: not firefox_profile_output.stat.exists
  tags:
    - install_client
    - firefox

# --------------------------------------------------------------------------
- name: "CLIENT | firefox setup | ensure directory exists for profile {{ install_client_firefox_profile_name }}"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.file:
    path: "~/{{ install_client_firefox_path }}/{{ install_client_firefox_profile_name }}/extensions/"
    state: directory
    mode: "0750"
  when:
    - is_firefox_installed.rc is defined
    - is_firefox_installed.rc == 0
  tags:
    - install_client
    - firefox

# --------------------------------------------------------------------------
- name: "CLIENT | firefox setup | download and install extensions for profile {{ install_client_firefox_profile_name }}"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "~/{{ install_client_firefox_path }}/{{ install_client_firefox_profile_name }}/extensions/{{ item.id }}.xpi"
    mode: "0640"
  loop: "{{ install_client_firefox_ext | flatten(levels=1) }}"
  when:
    - is_firefox_installed.rc is defined
    - is_firefox_installed.rc == 0
  tags:
    - install_client
    - firefox

# ------------------------------------------------------------------------------
- name: "CLIENT | firefox setup | copy user.js for profile {{ install_client_firefox_profile_name }}"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.template:
    src: "firefox/user.js.j2"
    dest: "~/{{ install_client_firefox_path }}/{{ install_client_firefox_profile_name }}/user.js"
    mode: "0640"
  when:
    - is_firefox_installed.rc is defined
    - is_firefox_installed.rc == 0
  tags:
    - install_client
    - firefox
