---
# tasks file for install_client

# --------------------------------------------------------------------------
- name: "CLIENT | firefox setup | check if Firefox is installed"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.command: which firefox
  register: is_firefox_installed
  changed_when: false
  failed_when: false
  check_mode: false
  tags:
    - install_client
    - firefox

# --------------------------------------------------------------------------
- name: "CLIENT | firefox setup | check if default Firefox profile exists"
  become: true
  become_user: "{{ outer_item.name }}"

  ansible.builtin.find:
    paths: "~/{{ install_client_firefox_path }}"
    recurse: false
    patterns: "*.default"
    file_type: directory
  register: install_client_firefox_default_profile_name_tmp
  tags:
    - install_client
    - firefox

- name: "CLIENT | firefox setup | save default profile name"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.set_fact:
    install_client_firefox_profile_name: "{{ install_client_firefox_default_profile_name_tmp.files[0].path | basename }}"
  when: install_client_firefox_default_profile_name_tmp.matched > 0
  tags:
    - install_client
    - firefox

# --------------------------------------------------------------------------
- name: "CLIENT | firefox setup | create new Firefox profile"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.command: "firefox --headless --createprofile {{ install_client_firefox_profile_name }}"
  register: create_new_profile
  changed_when: create_new_profile.rc == 0
  when: not install_client_firefox_default_profile_name_tmp.matched > 0
  tags:
    - install_client
    - firefox

- name: "CLIENT | firefox setup | save new created profile name"
  become: true
  become_user: "{{ outer_item.name }}"
  when: not install_client_firefox_default_profile_name_tmp.matched > 0
  tags:
    - install_client
    - firefox
  block:
    - name: "CLIENT | firefox setup | save new created profile name | search folder"
      ansible.builtin.find:
        paths: "~/{{ install_client_firefox_path }}"
        recurse: false
        patterns: "*.{{ install_client_firefox_profile_name }}"
        file_type: directory
      register: install_client_firefox_profile_name_tmp
    - name: "CLIENT | firefox setup | save new created profile name | save folder"
      ansible.builtin.set_fact:
        install_client_firefox_profile_name: "{{ install_client_firefox_profile_name_tmp.files[0].path | basename }}"
      when: install_client_firefox_profile_name_tmp.matched > 0

- name: "CLIENT | firefox setup | ensure directory exists for profile {{ install_client_firefox_profile_name }}"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.file:
    path: "~/{{ install_client_firefox_path }}/{{ install_client_firefox_profile_name }}/extensions/"
    state: directory
    mode: "0750"
  when:
    - not install_client_firefox_default_profile_name_tmp.matched > 0
    - is_firefox_installed.rc is defined
    - is_firefox_installed.rc == 0
  tags:
    - install_client
    - firefox

# # --------------------------------------------------------------------------
# - name: "CLIENT | firefox setup | download and install extensions for profile {{ install_client_firefox_profile_name }}"
#   become: true
#   become_user: "{{ outer_item.name }}"
#   when:
#     - is_firefox_installed.rc is defined
#     - is_firefox_installed.rc == 0
#   tags:
#     - install_client
#     - firefox
#   block:
#     - name: "CLIENT | firefox setup | download and install extensions | download"
#       ansible.builtin.get_url:
#         url: "{{ item.url }}"
#         dest: "~/{{ install_client_firefox_path }}/{{ install_client_firefox_profile_name }}/extensions/{{ item.id }}.xpi"
#         mode: "0640"
#       loop: "{{ install_client_firefox_ext | flatten(levels=1) }}"
#     - name: "CLIENT | firefox setup | download and install extensions | install"
#       ansible.builtin.command: "firefox --headless ~/{{ install_client_firefox_path }}/{{ install_client_firefox_profile_name }}/extensions/{{ item.id }}.xpi"
#       register: install_firefox_ext
#       changed_when: install_firefox_ext.rc == 0
#       loop: "{{ install_client_firefox_ext | flatten(levels=1) }}"

# ------------------------------------------------------------------------------
- name: "CLIENT | firefox setup | copy user.js for profile {{ install_client_firefox_profile_name }}"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.template:
    src: "firefox/user-combined.js.j2"
    dest: "~/{{ install_client_firefox_path }}/{{ install_client_firefox_profile_name }}/user.js"
    mode: "0640"
  when:
    - is_firefox_installed.rc is defined
    - is_firefox_installed.rc == 0
  tags:
    - install_client
    - firefox

- name: "CLIENT | firefox setup | copy containers.json for profile {{ install_client_firefox_profile_name }}"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.template:
    src: "firefox/containers.json"
    dest: "~/{{ install_client_firefox_path }}/{{ install_client_firefox_profile_name }}/containers.json"
    mode: "0640"
  when:
    - is_firefox_installed.rc is defined
    - is_firefox_installed.rc == 0
  tags:
    - install_client
    - firefox
