---
# tasks file for install_client

# ------------------------------------------------------------------------------
- name: "CLIENT | setup other | change Connectivity Checking to off - check if file exists"
  become: true
  ansible.builtin.stat:
    path: /var/lib/NetworkManager/NetworkManager-intern.conf
  register: file_stat_network_manager_intern_conf

- name: "CLIENT | setup other | change Connectivity Checking to off"
  become: true
  ansible.builtin.lineinfile:
    path: /var/lib/NetworkManager/NetworkManager-intern.conf
    regexp: '^\[connectivity\]'
    line: "[connectivity]"
    insertbefore: '^\.set\.enabled='
    state: present
  register: change_connectivity_checking_01
  when:
    - file_stat_network_manager_intern_conf is defined
    - file_stat_network_manager_intern_conf.stat is defined
    - file_stat_network_manager_intern_conf.stat.exists is defined
    - file_stat_network_manager_intern_conf.stat.exists
  tags:
    - install_client
    - other
    - connectivity_checking

- name: "CLIENT | setup other | change Connectivity Checking to off"
  become: true
  ansible.builtin.lineinfile:
    path: /var/lib/NetworkManager/NetworkManager-intern.conf
    regexp: '^\.set\.enabled='
    line: ".set.enabled=false"
    insertafter: '^\[connectivity\]'
    state: present
  register: change_connectivity_checking_02
  when:
    - file_stat_network_manager_intern_conf is defined
    - file_stat_network_manager_intern_conf.stat is defined
    - file_stat_network_manager_intern_conf.stat.exists is defined
    - file_stat_network_manager_intern_conf.stat.exists
  tags:
    - install_client
    - other
    - connectivity_checking

- name: "CLIENT | setup other | restart NetworkManager for changed Connectivity Checking"
  become: true
  ansible.builtin.service:
    name: NetworkManager
    state: restarted
    enabled: true
  when: >
    (
      change_connectivity_checking_01 is defined
      and change_connectivity_checking_01.changed is defined
      and change_connectivity_checking_01.changed | bool
    ) or
    (
      change_connectivity_checking_02 is defined
      and change_connectivity_checking_02.changed is defined
      and change_connectivity_checking_02.changed | bool
    )
  tags:
    - install_client
    - other
    - connectivity_checking
