---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-install-client"
      ansible.builtin.include_role:
        name: "ansible-install-client"
  vars:
    # --- in inventory ---
    clients:
      - name: "ubuntu"
        dev: true
        updateOrCreate: false
        setup: true # if client should be setup with additional tools and gui (default true)
    # --- in playbook ---
    # ------------------------------------------------------------------------------
    install_client_links_to_check_update_virtualbox: https://download.virtualbox.org/virtualbox/7.0.14/virtualbox-7.0_7.0.14-161095~Ubuntu~jammy_amd64.deb
    install_client_links_to_check_update_veracrypt: https://launchpad.net/veracrypt/trunk/1.26.7/+download/veracrypt-1.26.7-Ubuntu-23.04-amd64.deb
    install_client_links_to_check_update_veracrypt_cli: https://launchpad.net/veracrypt/trunk/1.26.7/+download/veracrypt-console-1.26.7-Ubuntu-23.04-amd64.deb
    install_client_links_to_check_update_parsec: https://builds.parsecgaming.com/package/parsec-linux.deb
    install_client_links_to_check_update_brim: https://github.com/brimdata/zui/releases/download/v1.5.0/zui_1.5.0_amd64.deb
    install_client_links_to_check_update_portmaster: https://updates.safing.io/latest/linux_amd64/packages/portmaster-installer.deb
    install_client_links_to_check_update_logseq: https://github.com/logseq/logseq/releases/download/0.10.5/Logseq-linux-x64-0.10.5.AppImage
    install_client_links_to_check_update_logseq_checksum: 17761baa0bcbd383f49d76885642650aaff3f21504d0cd14bad901b36a26b811 # pragma: allowlist secret
    install_client_links_tp_check_update_ultimaker: https://github.com/Ultimaker/Cura/releases/download/5.6.0/UltiMaker-Cura-5.6.0-linux-X64.AppImage
    install_client_links_tp_check_update_ultimaker_checksum: 107896a0da4b2873f3bfaad9aed36012bef2fff89571161e57f4da0a7f10a440 # pragma: allowlist secret

    install_client_config:
      # GENERAL -------------------------------
      dev: true
      fonts_install: true
      # GNOME ---------------------------------
      gnome_gui_setup: true # general of gnome setup should be triggered, below specific what (dependencies will than general installed)
      # gnome_gui_setup_dependencies: false
      gnome_gui_setup_extensions: true
      # gnome_gui_setup_extensions_apt_ubuntu_tiling: false
      # gnome_gui_setup_extensions_git_caffeine: false
      # gnome_gui_setup_extensions_git_sound: false
      gnome_gui_setup_extensions_git_blur_shell: true
      gnome_gui_setup_extensions_git_burn_window: true
      gnome_gui_setup_extensions_git_dash_to_panel: true
      gnome_gui_setup_extensions_git_ui_tune: true
      # gnome_gui_setup_keybinding: false
      gnome_gui_setup_overlay: true
      # gnome_terminal_setup_overlay: false
      cleanup_remove_snap: false
      cleanup_remove_flatpak: false
      # APT -----------------------------------
      apt_base: true
      apt_auth_priv: true
      apt_ubuntu: true
      apt_archive: true
      apt_codec: true
      apt_gnome: true
      apt_snap: true
      apt_flatpak: true
      apt_vpn_resolvconf: true
      apt_vpn_wireguard: true
      apt_vpn_openvpn: true
      apt_vpn_openconnect: true
      apt_vpn_l2tp: true
      # apt_gnome_boxes: false
      # apt_texmaker: false
      # apt_latex: false
      # apt_pandoc: false
      # apt_virt_viewer: false
      # apt_logitech_unifying_solaar: false
      # apt_mpv: false
      # DPKG ----------------------------------
      # dpkg_virtualbox: false
      # dpkg_veracrypt: false
      dpkg_veracrypt_cli: true
      # dpkg_parsec: false
      dpkg_brim: true
      dpkg_portmaster: true
      # DIST KEY ------------------------------
      # distribution_key_virtualbox: false
      distribution_key_1password_cli: true
      # APPIMAGE ------------------------------
      app_image_logseq: true
      app_image_ultimaker: true
      # SNAP ----------------------------------
      snap_nmap: true
      snap_john_the_ripper: true
      # FLATPAK -------------------------------
      flatpak_easy_effects: true
      flatpak_missioncenter: true
      # OTHER --------------------------------
      # vs_code_ext: false
