---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-install-client"
      include_role:
        name: "ansible-install-client"
  vars:
    # --- in inventory ---
    clients:
      - name: "ubuntu"
        dev: true
        updateOrCreate: false
        setup: true # if client should be setup with additional tools and gui (default true)
    # --- in playbook ---
    install_client_service_name: "{{ service_name }}"
    # if you install java, by default as version is set 11, change below if you need
    # version is as input for openjdk java version
    install_client_java_version: 11
    install_client_config:
      # GENERAL -------------------------------
      dev: true
      fonts: true
      # GNOME ---------------------------------
      gnome_gui_setup: true # general of gnome setup should be triggered, below specific what (dependencies will than general installed)
      # gnome_gui_setup_theme: false
      # gnome_gui_setup_dependencies: false
      gnome_gui_setup_extensions: true
      # gnome_gui_setup_keybinding: false
      gnome_gui_setup_overlay: true
      # cleanup_remove_snap: false
      # cleanup_remove_flatpak: false
      # APT -----------------------------------
      apt_base: true
      # apt_base_sound_pulseaudio: false
      apt_snap: true
      apt_flatpak: true
      apt_vpn: true
      # apt_gnome_boxes: false
      # apt_latex: false
      # apt_pandoc: false
      # apt_virt_viewer: false
      # DPKG ----------------------------------
      # dpkg_virtualbox: false # TODO: not working download
      dpkg_veracrypt: true
      # dpkg_parsec: false # TODO: not installable because of missing libavcodec58
      dpkg_brim: true
      dpkg_portmaster: true
      # DIST KEY ------------------------------
      # distribution_key_virtualbox: false
      # SNAP ----------------------------------
      snap_firefox: true
      snap_chromium: true
      snap_thunderbird: true
      # snap_signal_desktop: false
      # snap_telegram_desktop: false
      # snap_zoom_client: false
      # snap_spotify: false
      # snap_libreoffice: false
      snap_onlyoffice_desktopeditors: true
      # snap_inkscape: false
      # snap_drawio: false
      # snap_gimp: false
      # snap_darktable: false
      # snap_pixelfx: false
      # snap_lunacy: false
      # snap_vlc: false
      # snap_obs_studio: false
      # snap_flameshot: false
      # snap_1password: false
      # snap_okular: false
      # snap_yubioath_desktop: false
      # snap_code: false
      # snap_remmina: false
      # snap_android_studio: false
      # snap_UBports: false
      # snap_insomnia: false
      # snap_postman: false
      # snap_dbeaver_ce: false
      # snap_beekeeper_studio: false
      # snap_mqtt_explorer: false
      # snap_zaproxy: false
      snap_nmap: true
      # snap_john_the_ripper: false
      # snap_microk8s: false
      # snap_rpi_imager: false
      snap_multipass: true
      # snap_maas: false
      # snap_cornyjokes: false
      # snap_steam: false
      # FLATPAK -------------------------------
      # flatpak_flatseal: false
      # flatpak_firefox: false
      # flatpak_chromium: false
      # flatpak_thunderbird: false
      # flatpak_extension_manager: false
      # flatpak_flameshot: false
      # flatpak_onlyoffice: false
      # flatpak_1password: false
      # flatpak_keepassxc: false
      flatpak_easy_effects: true
      flatpak_signal: true
      # flatpak_telegram: false
      # flatpak_threemaqt: false
      # flatpak_zoom: false
      # flatpak_teams: false
      # flatpak_discord: false
      # flatpak_spotify: false
      # flatpak_ferdi: false
      # flatpak_vlc: false
      # flatpak_inkscape: false
      # flatpak_drawio: false
      # flatpak_gimp: false
      # flatpak_krita: false
      # flatpak_studio: false
      # flatpak_blender: false
      # flatpak_peek: false
      # flatpak_video_trimmer: false
      # flatpak_tube_converter: false
      # flatpak_girens: false
      # flatpak_code: false
      # flatpak_remmina: false
      # flatpak_sublimetext: false
      # flatpak_arduinoide: false
      # flatpak_fritzing: false
      # flatpak_insomnia: false
      # flatpak_postman: false
      # flatpak_dbeavercommunity: false
      # flatpak_mongodb_compass: false
      # flatpak_filezilla: false
      # flatpak_jdownloader: false
      # flatpak_wireshark: false
      # flatpak_ghidra: false
      # flatpak_zaproxy: false
      # flatpak_steam: false
      # flatpak_lutris: false
      # flatpak_ausweisapp2: false
      # flatpak_betaflightconfigurator: false
      # OTHER --------------------------------
      # vs_code_ext: false
      java: true
      java_ant: false
